// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api.Data;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220329131011_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("api.Models.Crm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Analyse")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Creation")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Debut")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Deroulement")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Diligence")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Fin")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Instruction")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Introduction")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Modification")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Objet")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Crms");
                });

            modelBuilder.Entity("api.Models.Crr", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Creation")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Debut")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DebutProchain")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Diligence")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EtatLieu")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Fin")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FinProchain")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Fonction")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Information")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Introduction")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Lieu")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Modification")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Objet")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Pj")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Presidence")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Redacteur")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Crrs");
                });

            modelBuilder.Entity("api.Models.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Analyse")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Contexte")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Creation")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Instruction")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Modification")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Objet")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Problematique")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Recommandation")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Redacteur")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("Creation")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Modification")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
